version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    
    volumes:
      - type: volume
        source: ${DB_VOLUME:-none}
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "${DB_CPU_LIMIT}"
          memory: "${DB_MEM_LIMIT}"
    networks:
      - branch_net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_api
    environment:
      FLASK_ENV: ${FLASK_ENV}
      DATABASE_URL: ${DATABASE_URL}
      LOG_LEVEL: ${LOG_LEVEL}
      PORT: ${API_PORT}
      PYTHONPATH: /app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_PORT}:${API_PORT}"
    command: ["/start_api.sh"]
    deploy:
      resources:
        limits:
          cpus: "${API_CPU_LIMIT}"
          memory: "${API_MEM_LIMIT}"
    networks:
      - branch_net

  nginx:
    image: nginx:stable-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/certs:/etc/nginx/certs:ro
    depends_on:
      - api
    networks:
      - branch_net


volumes:
  db_data_prod:
  none:

networks:
  branch_net:
    driver: bridge

